Added classic CQRS flow in .NET
EventStore/samples pull request #1
Opened 2021-07-14 14:47 UTC by oskardudycz

2021-07-19 10:22 UTC, ylorph requested changes

2021-07-19 11:48 UTC, oskardudycz commented on README.md
> +We're open for any contribution! If you noticed some inconsistency, missing piece, or you'd like to extend existing samples - we'll be happy to [get your Pull Request](https://github.com/EventStore/s
Yes, I wrote about that in the Contribution guidelines.

2021-07-19 11:51 UTC, oskardudycz commented on CONTRIBUTING.md
> +3. Pull request will be merged when you get approvals from at least 2 of the maintainers (and no rejection from others). Pull request will be tagged with the target Marten version in which it will be
Too much of copy/paste ;) Fixed in https://github.com/EventStore/samples/pull/1/commits/21ebc2d614ccbb3fc6b7581d722a1e2ac9f7e1c3.

2021-07-19 11:52 UTC, oskardudycz commented on CONTRIBUTING.md
> +Coding rules are set up in the project files with `.editorconfig` or `.prettierrc.json`. Those files are supported by all popular IDE (e.g. Microsoft Visual Studio, Rider, Visual Studio Code). Unless
Reworded that a bit in https://github.com/EventStore/samples/pull/1/commits/21ebc2d614ccbb3fc6b7581d722a1e2ac9f7e1c3. @ylorph could you have a look again?

2021-07-19 11:53 UTC, oskardudycz commented on README.md
> +This repository provides real-world, practical samples both for the [EventStoreDB](https://www.eventstore.com/) and clients SDK.
Reworded in https://github.com/EventStore/samples/pull/1/commits/21ebc2d614ccbb3fc6b7581d722a1e2ac9f7e1c3.

2021-07-19 11:53 UTC, oskardudycz commented
@ylorph, I think that I applied or answered or your comments. Thanks for checking that :+1: Good feedback.

2021-07-20 07:32 UTC, ylorph commented on README.md
> +We're open for any contribution! If you noticed some inconsistency, missing piece, or you'd like to extend existing samples - we'll be happy to [get your Pull Request](https://github.com/EventStore/s
no you're right

2021-07-20 07:33 UTC, ylorph approved these changes

2021-07-20 12:18 UTC, mat-mcloughlin approved these changes

2021-07-20 12:39 UTC, merged